# Generated by Django 3.2.13 on 2022-05-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_author_customuser'),
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
